from typing import Protocol

class DataRepository(Protocol):
    # Contrato: devolver el catálogo de productos para que las tools apliquen sus filtros.
    def get_products(self) -> list[dict]: ...
    # Contrato: devolver los tipos de evento reconocidos por la fuente de datos.
    def get_event_types(self) -> list[str]: ...
    # Contrato: consultar la compatibilidad o afinidad de un producto con un tipo de evento.
    def get_affinity(self, product_id: str, event_type: str) -> int: ...
    # Contrato: indicar si un producto tiene cobertura en la ubicación consultada.
    def get_coverage(self, product_id: str, location: str) -> bool: ...
    # Contrato: devolver las unidades disponibles de un producto en una fecha.
    def get_availability(self, product_id: str, date: str) -> int: ...
    # Contrato: devolver preferencias solo con identidad confiable y consentimiento registrado.
    def get_preferences(self, customer_id: str | None) -> list[str]: ...
    # Contrato: obtener el precio oficial de un producto como texto para cálculos con Decimal.
    def get_price(self, product_id: str) -> str: ...
    # Contrato: devolver la configuración de negocio necesaria para las reglas determinísticas.
    def get_config(self) -> dict: ...
